apiVersion: apps/v1
kind: Deployment
metadata:
  name: harrier-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harrier
  template:
    metadata:
      labels:
        app: harrier
    spec:
      containers:
      - name: harrier
        image: lorexdocker/embedding-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_NAME
          value: "harrier"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"